### ISSUE TITLE
_.collections.walk is broken

### ISSUE THREAD

**Issue by verticalpalette** [node4good/lodash-contrib#53]
```
> var _ = require('lodash-contrib');
Expression assignment to _ now disabled.
undefined
> _.walk.preorder({a: {b: true}}, function(x, y, z) { console.log(x); });
{ a: { b: true } }
TypeError: _.any is not a function
    at _walk (/Users/daniel/Code/src/github.com/trythings/trythings/node_modules/lodash-contrib/common-js/_.collections.walk.js:48:22)
    at walkImpl (/Users/daniel/Code/src/github.com/trythings/trythings/node_modules/lodash-contrib/common-js/_.collections.walk.js:56:7)
    at Object.preorder (/Users/daniel/Code/src/github.com/trythings/trythings/node_modules/lodash-contrib/common-js/_.collections.walk.js:145:7)
    at Function.wrapper [as preorder] (/Users/daniel/Code/src/github.com/trythings/trythings/node_modules/lodash/lodash.js:4968:19)
    at repl:1:8
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
```

The problem is that `walkImpl` calls `_.any`, but `_.any` was removed in `lodash@4.0.0` in favor of some (https://github.com/lodash/lodash/wiki/Changelog#v400).

I'm not sure why the tests for `_.collections.walk` don't catch this.

**Comment by rbinsztock** [comment]
Hi 

I already added a PR for this : https://github.com/node4good/lodash-contrib/pull/54 waiting to be merged, you can use my fixed fork if you want : https://github.com/rbinsztock/lodash-contrib
